sanctuary-js/sanctuary

index.js, test/index.js
`Maybe Number` better expresses the return type than `Number` (with NaN). See purescript/purescript-globals#5 for related discussion.
=> parse: add S.parseFloat and S.parseInt

index.js, test/index.js
> __encase__
> _verb_
> enclose or cover in a case or close-fitting surround
As I imagine it we're _encasing_ a function which may explode in an indestructible wrapper. Alternative name suggestions welcome.
=> maybe: add S.encase

index.js, test/index.js
The immediate motivation for this change is to enable `filter` to be defined for Maybe as suggested by @joneshf in #10. Implementing these specifications for Maybe is a good idea regardless.
=> maybe: implement Semigroup and Monoid

index.js, test/index.js
This makes Maybe compatible with `R.filter` and, if ramda/ramda#799 is merged, with `R.reject`.
@joneshf, would you mind reviewing this to make sure I faithfully translated the first of the laws you gave me?
=> maybe: define "filter"

index.js, test/index.js
`S.gets` allows one to do safe, nested property lookups. Nested property lookups are so common (and error prone) in JS that I think this would be a handy method to have around.
Compare the current method
```javascript
const obj = {foo: {bar: {baz: 'qux'}}};
const maybe_qux =  R.pipe(S.get('foo'),
R.chain(S.get('bar')),
R.chain(S.get('baz')))(obj)
```
with `S.gets`
```javascript
const maybe_qux = S.gets(['foo', 'bar', 'baz'], obj);
```
As far as implementation details, the non-reduce option is
```javascript
var gets = curry(function(keys, obj) {
var acc = Just(obj)
for (var idx = 0, len = keys.length; idx < len; idx += 1) {
acc = acc.chain(get(keys[idx]));
}
return acc;
});
```
And `S.gets([], obj)` will return `S.Just(obj)`.
=> add gets function and tests

index.js, test/index.js
The internal `arity` function uses the `Function` constructor to avoid the [wall of text][1] used to define `R.arity`.
[1]: https://github.com/ramda/ramda/blob/v0.13.0/src/arity.js#L32-L43
=> report lengths of exported functions correctly

index.js, test/index.js
This is the (`R.always`) implementation suggested by @aaditmshah in https://github.com/ramda/ramda/issues/732#issuecomment-70383334. It may be too strict for Ramda, but it feels right at home here.
=> combinator: add S.K

README.md
I kept having to refer to the tests to remember the names of the list and object functions I wanted to use so I decided to add descriptions of them to the docs. I didn't add `S.gets` yet because it's not in the version on NPM.
=> Add Documentation for List and Object Functions

README.md, index.js, package.json, test/index.js
Recent discussion in #15 and #20 has made it apparent that Sanctuary should depend on Ramda, in addition to working nicely alongside it. We've so far duplicated two significant Ramda functions solely for internal use: `curry` and `arity`. As Sanctuary grows this list could easily expand to include `map`, [`toString`][1], and other functions I'd very much like to avoid duplicating.
Furthermore, every Ramda function supports the [`R.__`][2] placeholder thanks to [`R.curry`][3]. Sanctuary functions lack this useful characteristic. Sanctuary could, of course, provide its own placeholder value, but since Sanctuary is a companion to rather than a replacement for Ramda, reusing Ramda's placeholder value is a better option.
[1]: https://github.com/ramda/ramda/pull/924
[2]: …
=> add Ramda dependency

index.js, package.json, test/index.js
This grants Maybe objects and Either objects the following property:
eval(R.toString(x)) ≍ x
While this is primarily useful in the REPL, it also makes these values compatible with [`R.memoize`][1].
This change was made possible by ramda/ramda#924 and the publication of Ramda v0.14.0. I love it when a plan comes together. :grinning:
[1]: http://ramdajs.com/docs/#memoize
=> maybe, either: define "toString"

.jshintrc, index.js
<http://jshint.com/docs/options/#unused>:
> This can be set to `vars` to only check for variables, not function parameters, or `strict` to check all variables and parameters. The default (true) behavior is to allow unused parameters that are followed by a used parameter.
Removing a function's unreferenced parameters is not an option. Doing so would alter the function's `length`, an extremely significant property in a world of currying and partial application.
=> lint: allow unused parameters

index.js, test/index.js
@joneshf and I discussed Either on Gitter. We couldn't think of a way to implement [Monoid][1] because Either doesn't have a canonical empty value. [Semigroup][2], though, seems completely reasonable. `Left.prototype.concat` and `Right.prototype.concat` are similar to `Just.prototype.concat`.
```javascript
> R.concat(S.Left('abc'), S.Left('def'))
Left('abcdef')
> R.concat(S.Left('abc'), S.Right([1, 2, 3]))
Right([1, 2, 3])
> R.concat(S.Right([1, 2, 3]), S.Left('abc'))
Right([1, 2, 3])
> R.concat(S.Right([1, 2, 3]), S.Right([4, 5, 6]))
Right([1, 2, 3, 4, 5, 6])
```
[1]: https://github.com/fantasyland/fantasy-land#monoid
[2]: https://github.com/fantasyland/fantasy-land#semigroup
=> either: implement Semigroup

.jscsrc, .jshintrc, index.js, test/index.js
This allows `S.and` and `S.or` to be applied to values of the Either type:
```javascript
> S.and(S.Left('abc'), S.Left('xyz'))
Left('abc')
> S.and(S.Left('abc'), S.Right(1))
Left('abc')
> S.and(S.Right(1), S.Left('abc'))
Left('abc')
> S.and(S.Right(1), S.Right(2))
Right(2)
> S.or(S.Left('abc'), S.Left('xyz'))
Left('xyz')
> S.or(S.Left('abc'), S.Right(1))
Right(1)
> S.or(S.Right(1), S.Left('abc'))
Right(1)
> S.or(S.Right(1), S.Right(2))
Right(1)
```
`S.xor` cannot be applied to values of the Either type since the type lacks a canonical empty value:
```javascript
> S.xor(S.Left('abc'), S.Left('xyz'))
TypeError: Left("abc") does not have an "empty" method
```
For the sake of consistency, an error is thrown even when the empty value is not needed:
```javascript
> S.xor(S.Left('abc'), …
```
=> either: define "toBoolean"

index.js, test/index.js
[`Object.is`][1] and [`R.eq`][2] also have [SameValue][3] semantics. It's possible we should switch to [`R.eqDeep`][4] semantics, but we certainly don't want `===` semantics.
[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is
[2]: http://ramdajs.com/0.14/docs/#eq
[3]: http://people.mozilla.org/~jorendorff/es6-draft.html#sec-samevalue
[4]: http://ramdajs.com/0.14/docs/#eqDeep
=> maybe, either: give "equals" methods ES6 SameValue semantics

index.js, test/index.js
Resolves #28 . I've actually been using R.compose with Sanctuary to create a safe version of `R.match` quite a few times recently so I thought I'd have a stab at a PR for this. The implementation is simple enough:
```javascript
S.match = R.curry(function (regex, s) {
return R.compose(S.toMaybe, R.match(regex))(s);
});
```
But I was having problems writing the tests. Obviously because `R.match` returns an array, if I do something like:
```javascript
assert(S.match(/abcd/, 'abcdefg').equals(S.Just(['abcd']))
```
it fails because `Just.equals` is checking by reference.
If I do
```javascript
assert.deepEqual(S.match(/abcd/, str), S.Just(['abcd']));
```
it fails because `match` gives back this mad arraylike object with the object keys `input` and `index` so I find myself having to do this in …
=> Add S.match function

.jscsrc, CONTRIBUTING.md, Makefile, index.js, package.json, scripts/prepublish
Closes #22
Until @svozza contributed #19, Sanctuary's API was completely undocumented. It's currently partially documented. This pull request documents the rest of the API, and adds a section on types and how to read Sanctuary's type signatures.
Points of note:
- The source of the documentation is __index.js__. __README.md__ is now derived from the source via [Transcribe][1].
- I've included the changes to [__README.md__][2] for the benefit of those reviewing the pull request. I will revert these changes before merging this pull request as the file will be updated automatically with each release.
- To generate [__README.md__][2] I ran `VERSION=0.4.0 make`. As a result, the line numbers to which the headings in the API section link are not correct. This will not be a problem when the file …
=> add documentation and Transcribe-powered prepublish script

test/index.js
This pull request improves our assertions in two ways:
- By using value-based equality we can now write
```javascript
eq(S.parseJson('["foo","bar"]'), S.Just(['foo', 'bar']));
```
rather than
```javascript
var xs = S.fromMaybe(null, S.parseJson('["foo","bar"]'));
eq(Object.prototype.toString.call(xs), '[object Array]');
eq(xs.length, 2);
eq(xs[0], 'foo');
eq(xs[1], 'bar');
```
- By comparing string representations we get a useful error message when an assertion fails. For example,
```javascript
eq(S.Just(['1', '2', '3']), S.Just([1, 2, 3]));
// AssertionError: 'Just(["1", "2", "3"])' === 'Just([1, 2, 3])'
```
rather than
```javascript
assert(S.Just(['1', '2', '3']).equals(S.Just([1, 2, 3])));
// AssertionError: false == true
```
=> test: compare string representations in eq

test/index.js
The tests should assert exactly which constructor was used to create a particular Error object. `R.is(Error, error)` evaluates true even if `error` has a more specific type such as TypeError.
=> test: compare Error objects by constructor

index.js, test/index.js
[`R.indexOf`][1] and [`R.lastIndexOf`][2] now dispatch thanks to ramda/ramda#1113. [`R.slice`][3] has dispatched in its current manner since [v0.8.0][4].
[1]: http://ramdajs.com/docs/#indexOf
[2]: http://ramdajs.com/docs/#lastIndexOf
[3]: http://ramdajs.com/docs/#slice
[4]: https://github.com/ramda/ramda/blob/v0.8.0/ramda.js#L3542
=> list: document string support by S.indexOf, S.lastIndexOf, and S.slice

.jscsrc, index.js, test/index.js
Sanctuary currently does type checking in a few places (as those of use who've seen `Pattern match failure` logged to our console can attest). This pull request addresses two problems with the status quo:
- when a TypeError is thrown, the error message is rarely helpful; and
- the site at which a TypeError is thrown is often one or more steps removed from the type mismatch.
See what happens when we provide arguments to a function in the wrong order:
```javascript
S.at(['foo', 'bar', 'baz'], 1);
// TypeError: at requires a value of type Number as its first argument; received ["foo", "bar", "baz"]
```
Types are checked as arguments are applied:
```javascript
S.at('1');
// TypeError: at requires a value of type Number as its first argument; received "1"
```
This approach was proposed by …
=> systematic type checking

index.js, test/index.js
Defines an `extend` method for the `Either` type as per the [fantasyland](https://github.com/fantasyland/fantasy-land#extend) spec.
=> either: define extend

.jshintrc, index.js, test/index.js
Defines an `extend` method for the `Maybe` type as per the [fantasyland](https://github.com/fantasyland/fantasy-land#extend) spec.
=> maybe: define extend

.jshintrc, index.js, test/index.js
Added additional tests to check that the `extend` method satisfies the property laid out at https://github.com/fantasyland/fantasy-land#extend-method. Also fixes implementations to adhere to those specs.
=> extend: correct the behavior and add tests to check associativity

index.js, test/index.js
Before:
> S.and([], S.Nothing())
TypeError: Type mismatch
After:
> S.and([], S.Nothing())
TypeError: and requires its first and second arguments to be of the same type; [] and Nothing() are not
:memo: _Can anyone suggest improvements to the wording of this message?_
It turned out to be useful to have the implementation of the internal `curry` function further diverge from the approach used by Ramda. The recursive call now appears in this expression:
```javascript
return args.length === len ? f.apply(this, args)
: curry(name, types, values, f);
```
When `curry` recurses, the *same* function is provided. Only the third argument differs. In the application of `S.take` to `5`, `values` would be `[R.__, R.__]` initially and `[5, R.__]` in the recursive call.
I haven't checked whether this …
=> descriptive error messages for type mismatches

index.js, test/index.js
ramda/ramda#296 made the behaviour of `R.is` inconsistent for primitives:
```javascript
> R.is(Number, new Number(0))
true
> R.is(Object, new Number(0))
true
> R.is(Number, 0)
true
> R.is(Object, 0)
false
```
A primitive is promoted to its object equivalent in the case of `R.is(Number)` but not in the case of `R.is(Object)`.
By removing the `R.is(Object)` special case we're able to replace many occurrences of `a` and `b` with `Object` in the type definitions. This allows us to provide more helpful error messages. For example:
```
> S.head(null)
TypeError: head requires a value of type Object as its first argument; received null
```
We needn't expose `is`, but its more "correct" behaviour may be useful in other situations as well.
The one problem with this approach is that it disallows …
=> classify: add S.is

index.js, package.json
- ramda/ramda#1277
- ramda/ramda#1290
> :warning: `R.match` now returns `[]` rather than `null` when there are no matches ramda/ramda#1239
=> ramda@0.17.x

index.js, test/index.js
The fact that `S.get` returns a value of type `Maybe *` has bothered me for some time. I find myself filtering the result to ensure I have a value of the expected type. For example:
```javascript
R.pipe(...,
S.get('x'),
R.filter(R.is(Number)),
...)
```
This pull request adds a type specifier to `S.get`, `S.gets`, and `S.pluck`. The above will become:
```javascript
R.pipe(...,
S.get(Number, 'x'),
...)
```
The current loose behaviour can be approximated by `S.get(Object)`. It's no longer possible to get null/undefined values. If this is important we could export an Any pseudotype, where Any contains every JavaScript value. Unless there's a use case, I'd prefer not to export and document `S.Any`.
These changes build upon the foundation laid by #63. I've included a section explaining the …
=> add type argument to S.get, S.gets, and S.pluck

index.js, test/index.js
I basically just followed the `either` tests except for the 'is curried' part, as I noticed it was quite extensive but none of the other 'is curried' tests were.
I decided against including "eitherIfElse" for now. I pretty much only created it because it seemed like a decent idea and you can use it to define `maybeToEither`. If you really like the idea of, I'm happy to submit a PR, but I figured I'd just let it hang out in my code for a while and see how much I actually use it.
=> add maybeToEither

index.js, test/index.js
Closes #45
This pull request, like #62, makes the types of several functions more restrictive by requiring integer indices, radices, and slice lengths. It differs from #62 in two significant ways:
- it does not add any functions; and
- it introduces a pseudotype for (-2^53 .. 2^53) rather than [-2^31 .. 2^31).<sup>†</sup>
When I opened #45, I had two goals in mind: integer-specific functions, and stricter types for existing functions. My first solution was an Int container type. Others rightly pointed out that `S.at(S.Int(3))` is much less convenient than `S.at(3)`. Interacting with boxed numbers returned by functions such as `S.indexOf` would have been similarly awkward.
In #62 I proposed an Int pseudotype rather than an Int container type, obviating the need for boxing and unboxing. I …
=> add Integer pseudotype

index.js, test/index.js
Closes #72
`maybe :: b -> (a -> b) -> Maybe a -> b` proved useful in defining this function. I'll rebase this patch once #77 has been merged.
=> maybe: add S.catMaybes

index.js, test/index.js
Closes #73
`catMaybes :: [Maybe a] -> [a]` proved useful in defining this function. I'll rebase this patch once #78 has been merged.
=> maybe: add S.mapMaybe

index.js, test/index.js
This is another minor improvement to the descriptiveness of our type errors.
My only concern is the word used to describe values such as `[1, 2, 3]` and `'foo'`. Referring to these as lists is fine, but the way in which we detect such values is by consulting the `length` property. As @CrossEye is fond of saying, an actual List type would be a linked list. The length of a linked list is usually determined via a recursive function, so if one day we were to provide an actual List type, a value of that type may not be considered a member of the List pseudotype!
Perhaps "ArrayLike" is a better name for the pseudotype. What do you think?
=> add List pseudotype

circle.yml
I'm pleased to have learnt how to do this (from one of the members of the CircleCI support team).
=> circle: run tests on Node v0.12.x in addition to Node v0.10.x

.jscsrc, index.js, test/index.js
Closes #18
I used `ghci` and [§ 9.8.1][1] as references.
[1]: http://www.ecma-international.org/ecma-262/5.1/#sec-9.8.1
=> parse: disallow invalid characters in S.parseFloat

index.js, test/index.js
Ramda provides [`R.identity`][1], of course, but `S.I` is much shorter:
```javascript
S.encaseEither(R.identity, JSON.parse)
```
```javascript
S.encaseEither(S.I, JSON.parse)
```
Since we already provide `S.K`, it seems more fitting to name this function `I` rather than `id`.
[1]: http://ramdajs.com/docs/#identity
=> combinator: add S.I

index.js, test/index.js
Closes #84
I spent a surprisingly long time working this patch into its current form. I'm pleased with the current approach based on `assertMethodExists`.
=> maybe, either: descriptive errors for missing "concat" methods

bower.json, index.js
This pull request makes Sanctuary compatible with AMD module loaders such as [RequireJS][1], as requested by @ChetHarrison.
@CrisFeo, this patch ended up being far less convoluted than we initially feared it would need to be. :)
[1]: http://requirejs.org/
=> AMD compatibility

index.js, test/index.js
I proposed these functions in https://github.com/ramda/ramda/issues/1318#issuecomment-132005376. It's unlikely that Ramda will provide these exact functions but I happen to contribute to another functional programming library as well. ;)
The implementation of `compose` is wonderfully straightforward.
The implementation of `pipe` is elegant: a right fold over the list of functions, with `compose` as the reducing function and `identity` as the identity element.
I'm pleased with `meld` as the name of the third function. Is it appealing to others as well?
I'm interested to know whether this patch gets the @joneshf seal of approval; `compose` and `pipe` are intended to be easier to reason about than their Ramda counterparts.
I'd also like to hear from @CrossEye, @paldepind, and other Ramda …
=> composition: add S.compose, S.pipe, and S.meld

index.js
Using a curried compose function at every step of `S.pipe` incurs a pretty big performance hit. This leaves the external API unchanged, since `S.compose` and `S.pipe` are still curried.
=> use uncurried compose internally for S.pipe

Makefile, index.js
This change was motivated by a doctest in #99; ramda/ramda#1398 likely gave me the idea.
=> use arrow functions in doctests

index.js, test/index.js
Closes #97
I'm not thrilled about naming this function `regex` when the type's name is RegEx<strong>p</strong>, but `regexp` is inconsistent in its capitalization and `regExp` is unbearably ugly. `regex` seems the best of the three options.
Having dropped the "p" elsewhere, I'm happy to name the pseudotype RegexFlags (as PureScript does).
=> regexp: add S.regex

index.js, test/index.js
Like [`R.test`][1], but with the type checking we know and love. See ramda/ramda#1413 for a compelling example of the problems that arise due to Ramda's lack of type checking.
/cc @albrow
[1]: http://ramdajs.com/docs/#test
=> regexp: add S.test

index.js, package.json, test/index.js
This will obviate the need for dependencies such as [escape-regexp][1] when using Sanctuary.
I'm open to name suggestions. `escapeRegexMetachars` is more descriptive, but feels too long.
I copied the regular expression from [XRegExp][2].
This is the first time I've used [JSVerify][3]. I'm impressed. We should write more tests this way!
[1]: https://www.npmjs.com/package/escape-regexp
[2]: https://github.com/slevithan/xregexp/blob/v3.0.0/xregexp-all.js#L792-L806
[3]: https://github.com/jsverify/jsverify
=> regexp: add S.regexEscape

index.js
This PR simply proxies the `toString` method onto the `inspect` method to
make the Sanctuary types more REPL-friendly.
The Node REPL uses `util.inspect` when rendering objects for display.
This method defers to the `inspect` method on an object if it exists.
[source](https://nodejs.org/api/repl.html#repl_customizing_object_displays_in_the_repl)
=> Add an 'inspect' method to all types

index.js, test/index.js
The most elegant implementation of these would be something like:
```js
S.allPass = (preds, a) => R.reduce((acc, f) => f(a) && acc, true, preds);
```
But then we'd lose short-circuiting.
=> Add allPass and anyPass

index.js, test/index.js
See purescript/purescript-strings#54
`R.test` has always behaved this way. I simply forgot about this internal state when preparing #109.
=> regexp: make S.test referentially transparent for "global" patterns

bower.json, circle.yml, index.js, package.json
See the [0.18.0][1] and [0.19.0][2] upgrade guides.
I typically upgrade Ramda one minor version at a time, but I had trouble with one of the doctests when running 0.18.0, so I decided to skip that version. The changes are minimal, at any rate.
[1]: https://github.com/ramda/ramda/issues/1436
[2]: https://github.com/ramda/ramda/issues/1558
=> ramda@0.19.x

index.js, test/index.js
=> Implement S.add and S.sub

index.js, test/index.js
Implements #118 
As per the included docs:
**Maybe#sequence :: Applicative f => Maybe (f a) ~> (b -> f b) -> f (Maybe a)**
Evaluates an applicative action contained within the Maybe, resulting in:
- an applicative of `Just` the value of the evaluated action if `this`
is a `Just`.
- a pure applicative of `Nothing` if `this` is a `Nothing`.
```javascript
> S.Nothing().sequence(S.Either.of)
Right(Nothing())
> S.Just(Right(42)).sequence(S.Either.of)
Right(Just(42))
```
=> Add traversable instance for Maybe

index.js, test/index.js
```haskell
toUpper :: String -> String
toLower :: String -> String
```
This shouldn't be controversial. It's [`R.toUpper`][1] and [`R.toLower`][2], but with type checking. :)
[1]: http://ramdajs.com/docs/#toUpper
[2]: http://ramdajs.com/docs/#toLower
=> string: add S.toUpper and S.toLower

index.js
I noticed this while working on the nascent Sanctuary website, which will have a killer feature: every code example will be interactive! Essentially every function's documentation will have an accompanying REPL.
=> style: remove "S." prefix from doctest output values

index.js, test/index.js
This pull request introduces two straightforward functions:
```haskell
even :: Integer -> Boolean
odd  :: Integer -> Boolean
```
It also removes the internal `Integer` definition, which is unnecessary now that we have [`$.Integer`][1]. :)
Note: In many JavaScript libraries one would expect these functions to be named `isEven` and `isOdd`. In Haskell, though, they are simply `even` and `odd`. This feels right in Sanctuary since we also emphasize reasoning based on types rather than names.
It's wonderful how simple a function's implementation becomes when one is able to restrict its domain. We needn't decide what to do with inputs such as `0.5` and `Infinity`, in this case.
[1]: https://github.com/plaid/sanctuary-def#integer
=> integer: add S.even and S.odd

index.js, test/index.js
[`R.map`][1] and [`R.ap`][2] support Function, so we can assume that Function satisfies the requirements of [Apply][3].
This allows us to define `complement`, `both`, and `either` via lifting, as discussed in #102.
```javascript
//    complement :: Functor f => f Boolean -> f Boolean
const complement = S.lift(S.not);
//    both :: Apply f => f Boolean -> f Boolean -> f Boolean
const both = S.lift2(S.and);
//    either :: Apply f => f Boolean -> f Boolean -> f Boolean
const either = S.lift2(S.or);
//    isEven :: Integer -> Boolean
const isEven = x => x % 2 === 0;
//    isOdd :: Integer -> Boolean
const isOdd = complement(isEven);
//    isPositive :: Number -> Boolean
const isPositive = x => x > 0;
both(isEven, isPositive)(42);   // => true
both(isEven, isPositive)(43);   // => false …
```
=> function: assume that Function satisfies the requirements of Apply

index.js, test/index.js
This pull request adds Haskell's [`lefts`][1] and [`rights`][2]:
```haskell
lefts  :: [Either a b] -> [a]
rights :: [Either a b] -> [b]
```
I recently reviewed some code @Bpless wrote which could be nicely expressed in terms of `rights`.
These functions are similar to [`S.catMaybes`][3], which should arguably be renamed `S.justs` for consistency.
[1]: http://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Either.html#v:lefts
[2]: http://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Either.html#v:rights
[3]: https://github.com/plaid/sanctuary#catMaybes
=> either: add S.lefts and S.rights

index.js
There were a fair few instances of `R.inc` and friends in the docs...
=> Replace Instances of Ramda Functions in Docs With Sanctuary Equivalent

index.js, test/index.js
```haskell
min :: Ord a => a -> a -> a
max :: Ord a => a -> a -> a
```
[`R.min`][1] and [`R.max`][2], but with type checking. I want to tick some boxes in #145. :)
[1]: http://ramdajs.com/docs/#min
[2]: http://ramdajs.com/docs/#max
=> number, string: add S.min and S.max

index.js
`R.ifElse(R.isNil, Nothing, Just)` is misleading since `Nothing` is a nullary constructor. It *happens* to work because `Nothing` doesn't complain about the unexpected argument, but I don't like to rely on this.
=> refactor toMaybe to avoid applying Nothing to an argument

bower.json, index.js, package.json, test/index.js
`sanctuary-def@0.4.0` has not yet been released, but this needn't stop us from preparing.
In plaid/sanctuary-def#28 we made type checking optional. The most straightforward change would be to replace `$.create(env)` with `$.create(true, env)`. Sanctuary's slowness, though, was the motivation for making type checking optional in sanctuary-def, so Sanctuary must also provide a way to opt out of type checking.
The solution employed in this pull request is to provide two versions of the Sanctuary module: one with type checking; one without.
Sanctuary, with type checking:
```javascript
const S = require('sanctuary');
```
Sanctuary, without type checking:
```javascript
const S = require('sanctuary').unchecked;
```
=> sanctuary-def@0.4.x

index.js
In the current sanctuary version this code returns wrong result in IE 11:
`   S.is(Array, []) // It would be false`
The problem is in how sanctuary determines the type. More precisely how it compares user's constructor (Array) and the value from R.type() in 386th line:
`   R.type(x) === R.nth(1, R.match(/^function (\w*)/, String(type)))`
The actual problem is that this code returns different results in different browsers:
```
String(Array)
// In chrome — "function Array() { [native code] }"
// In IE 11  — "\nfunction Array() {\n    [native code]\n}\n"
```
ECMA 262 5.1 says that the result of String(Array) is not determined and the count of whitespaces depends on implementation:
> 15.3.4.2 Function.prototype.toString ( )
> An implementation-dependent representation of the function is …
=> S.is() returned wrong result in IE 11

Makefile, bower.json, index.js, package.json, test/index.js
Closes #165
/cc @Risto-Stevcev, @raqystyle, @soroushjp
> 1,582 additions, 216 deletions not shown because the diff is too large.
Since GitHub refuses to show the most exciting part of the patch—the improved error messages—I'll present a selection here.
Before:
```javascript
S.or(0, 1);
// ! TypeError: ‘or’ requires ‘a’ to implement Alternative; Number and FiniteNumber and Integer and ValidNumber do not
```
After:
```javascript
S.or(0, 1);
// ! TypeError: Type-class constraint violation
//
//   or :: Alternative a => a -> a -> a
//         ^^^^^^^^^^^^^    ^
//                          1
//
//   1)  0 :: Number, FiniteNumber, Integer, ValidNumber
//
//   ‘or’ requires ‘a’ to satisfy the Alternative type-class constraint; the value at position 1 does not.
```
Before:
```javascript
S.or([], …
```
=> sanctuary-def@0.5.x

index.js, test/index.js
Adds a second argument to the `parseJson` function: A TypeRep which the result from parsing the JSON is validated against. This closes #150.
=> Change parseJson to perform type validation

index.js, test/index.js
=> list: add S.concat

index.js, test/index.js
As discussed in #159. I've a few reservations about this, firstly if I define `S.prop` as `var prop = S.prop = def(...` then I get lots of errors in the tests when I replace instances of `R.prop` in `index.js`:
>TypeError: prop is not a function
at createSanctuary (/home/stefano/git/sanctuary/index.js:9:16296)
at /home/stefano/git/sanctuary/index.js:9:45767
at _ (/home/stefano/git/sanctuary/index.js:9:268)
at Object.<anonymous> (/home/stefano/git/sanctuary/index.js:9:779)
Another thing is that `Accessible` is a very permissive type for this function, it allows you to pass numbers or booleans in even though they don't support property access so you end up getting error messages that leak implementation details to the user:
```js
S.prop('a', true)
// => TypeError: Cannot use 'in' operator …
```
=> Add prop function

Makefile, test/Either/Either.js, test/Either/EitherType.js, test/Either/Left.js, test/Either/Right.js, test/Maybe/Just.js, test/Maybe/Maybe.js, test/Maybe/MaybeType.js, test/Maybe/Nothing.js
#185 caused problems for me on OS X, because __test/Either.js__ and __test/either.js__ are considered the same filename.
This pull request introduces __test/Either__ and __test/Maybe__ directories for the benefit of case-insensitive file systems.
=> rename files to support file systems which are not case-sensitive

index.js, test/justs.js
`justs` is consistent with [`lefts`][1] and [`rights`][2]. I consider it more important for Sanctuary to be internally consistent than it is to preserve Haskell's function names.
[1]: http://sanctuary.js.org/#lefts
[2]: http://sanctuary.js.org/#rights
=> maybe: rename S.catMaybes

index.js, test/maybeToNullable.js
=> maybe: add S.maybeToNullable

index.js
> This commit also updates type signatures to use `Array _` rather than `[_]` to represent the type of a value which really must be an array.
=> array: add section for array-specific functions

index.js, test/append.js
This adds S.append as suggested by #145 
So this is my first contribution and I just naively implemented it as `a -> [a] -> [a]`.
=> Add S.append

index.js, test/Either/Left.js, test/Either/Right.js
Closes #119
This is similar to #69. Does this patch look good to you, @scott-christopher?
=> either: implement Foldable

index.js, test/product.js, test/sum.js
I had to move a few functions to the top of the file so that we could replace the Ramda versions used throughout the code.
=> Add S.sum and S.product

index.js, test/append.js, test/prepend.js
=> array: add S.prepend

Makefile, bower.json, index.js, package.json, test/Either/EitherType.js, test/I.js, test/Maybe/MaybeType.js, test/product.js, test/sum.js
=> sanctuary-def@0.6.x

index.js, test/Maybe/Maybe.js, test/eitherToMaybe.js, test/match.js
=> either: add S.eitherToMaybe

index.js, test/keys.js, test/pairs.js, test/values.js
Creating a type-safe version of `R.keys` was mentioned in #142 and now that `StrMap` is available I thought I'd road test it a bit. The implementation of this will probably provoke discussion, firstly because I'm using an ES5 only implementation: I find the Ramda implementation far too complicated for what should be a simple function. Secondly, I've chosen not to implement `S.values` in terms of `S.keys` because I don't think it makes sense to pay the penalty of type checking the object twice.
=> Add S.keys, S.values and S.pairs

index.js
As a member of the council for de-Ramdification, I hearby declare this function purged.
=> Remove Ramda dependency in S.trim

index.js, test/T.js
In preparation for the upcoming v0.11.0 release I'm updating a rather large project to run against `sanctuary-js/sanctuary#master`. Now that we're embracing curried functions (#182), combinators seem more useful than ever (and `T` seems more useful to me than [`A`][1]).
[1]: http://sanctuary.js.org/#A
=> combinator: add S.T

index.js, test/reverse.js
=> Add S.reverse

index.js, test/fromEither.js
S.fromEither :: b -> Either a b -> b
Closes: #130
=> Add S.fromEither to pull out values from either

index.js, test/mean.js
I’ve implemented the `mean` function, as it’s been suggested in #194.
The tests are roughly based on `product` tests. One thing I couldn’t figure out is how to put a type constraint on the argument of type `f`, i.e. how to specify the function accepts only foldables of finite numbers. I’ve noticed neither `product` nor `sum` enforce this restriction on their argument, only on their results (even though the comments suggest they do: `product :: Foldable f => f FiniteNumber -> FiniteNumber`).
Passing a foldable with an infinite number to `mean` does not typecheck, but it fails on the call to `sum`, which makes the message a bit misleading.
=> Add S.mean that calculates mean of values of a foldable

package.json
This is just to get rid of that annoying warning message:
```
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```
=> Upgrade to version 3 of Mocha

index.js, test/toEither.js
A function for converting a possibly null-y value to an Either
Closes #83
=> Adds `toEither :: a -> b? -> Either a b`

Makefile, circle.yml, index.js
This addresses the test failure noted in #248.
As can be seen in the diff, we currently have a guard which prevents doctests from being run in Node v0.10.x (which doesn't support arrow functions). It's completely reasonable to run doctests in just one environment, since their purpose is to keep the documentation up to date rather than guarantee compatibility across Node versions. I suggest the latest stable version if we're to choose just one.
I hope these changes obviate the need to mention a version in __CONTRIBUTING.md__, as it would be easy for such a note to become out of date. Let's merge this pull request then discuss in #248 whether to add a note.
=> switch from Node v5.x.x to Node v6.x.x

index.js, test/Either/Left.js, test/Either/Right.js, test/Maybe/Just.js, test/Maybe/Nothing.js
This is the first of several improvements I plan to extract from #216 in order to make them easier to review. :)
=> expand documentation of type signatures and fix inconsistencies

index.js, test/indexOf.js, test/lastIndexOf.js
> This commit also fixes a bug in the List type's "extractor" which prevented it from returning list elements beyond the first.
=> list: remove ArrayLike type class

Makefile, index.js, test/Either/Left.js, test/Either/Right.js, test/Maybe/Just.js
It's nice to be able to define exported functions in terms of other exported functions without worrying about the performance cost of the additional type checking. The solution is to define a vanilla version of each exported function. By leveraging function hoisting we no longer need to consider the order of the function definitions, allowing `function(x) { return Just(x); }`, for example, to be replaced with `Just`.
`Just`, `Left`, and `Right` now perform type checking. This makes the property-based tests slower, so I increased the `--timeout` in the makefile's `test` target.
:icecream:
=> define vanilla version of each exported function for internal use

index.js, test/joinWith.js, test/splitOn.js
``` haskell
splitOn  :: String -> String -> Array String
joinWith :: String -> Array String -> String
```
Related:
- [`split`](http://ramdajs.com/0.22.1/docs/#split), [`join`](http://ramdajs.com/0.22.1/docs/#join) (Ramda)
- [`split`](https://pursuit.purescript.org/packages/purescript-strings/1.1.0/docs/Data.String#v:split), [`joinWith`](https://pursuit.purescript.org/packages/purescript-strings/1.1.0/docs/Data.String#v:joinWith) (PureScript)
At some point I'd like to add a Sanctuary equivalent of [`R.unnest`](http://ramdajs.com/0.22.1/docs/#unnest), which in Haskell is named [`join`](http://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Monad.html#v:join). I'd like to keep `S.join` open for this. Also, `joinWith` is more suggestive of a binary function than `join` is, so I consider …
=> string, array: add S.splitOn and S.joinWith

index.js, test/on.js, test/on_.js
Closes https://github.com/sanctuary-js/sanctuary/issues/281
=> Added function S.on

index.js, test/curry2.js, test/curry3.js, test/curry4.js, test/curry5.js
Hi, first pull request here. Thanks for the hand-holding. This closes #277. 
Things not complete or I'm not sure about: 
Looks like all of the examples in the readme are one liners. 
I have `function(v, w, x, y, z)`...
=> Curry: Add functions curry2 through curry5

index.js, test/pluck.js
=> Change pluck to be more prop-like

Makefile, circle.yml, index.js, karma.conf.js, package.json, test/mocha.opts
This PR when it's finished will add support for running the unit tests through Karma and hookup CircleCI to execute them on multiple browsers via SauceLabs, so that we can properly prove browser support and potentially resolve #292.
At the moment I have karma successfully being able to execute the test suite using browserify to handle the test suite translation to the browser (module loading mostly). Browserify adds a little bit of weight to DevDeps but does do a good job of bundling the tests correctly.
One thing I will probably want your input on @davidchambers is how to go about integrating the `karma start` command into the Makefile. Since we can run the tests in many different ways via karma:
- Simple quick test run using a headless browser (PhantomJS)
- Test manually by bringing …
=> Implement browser testing

package.json, test/Either/Either.js, test/Maybe/Maybe.js, test/internal/Compose.js, test/internal/EitherArb.js, test/internal/Identity.js, test/internal/IdentityArb.js, test/internal/MaybeArb.js
I've become aware of something which has been disrupting my flow. When working on a significant change I often find myself restructuring existing code to make it easier to modify or extend, but this has the effect of making my patch bigger (and scarier). My plan is to submit a preliminary pull request for the restructuring in such a case, so that the subsequent pull request for the significant change is easier to review.
This is a preliminary pull request. As it consists entirely of restructuring, it should be relatively easy to review. :)
=> test: share constructors to remove duplication

README.md, index.js
I kind of got spooked when I saw the build failing and saw the browsers tests dieing. After a bit I noticed the badge is just linked to all builds which I think is a bit confusing at times at can make it look like sanctuary is broken.
This PR changes the badge to only get the status from the master branch and to link to master branch builds on CircleCI.
=> Lock CircleCI badge to master branch

Makefile, README.md, bower.json, index.js, package.json, scripts/version-urls
Linking to things which can change is not a good idea. As a case in point, we currently have broken links as a result of sanctuary-js/sanctuary-def#97 (we link to `#nullable` rather than `#Nullable`, for example).
This pull request:
- introduces `version-urls`, a script which replaces specially formatted placeholders with version-specific function URLs; and
- updates __README.md__ to fix the broken links immediately (and remove the possibility of further breakages).
The second of these changes is a bit confusing, since it relates to `v0.11.1` (the most recent release) rather than to `master`. Some detective work is required to determine the appropriate dependency versions. :mag:
```console
$ npm view sanctuary@0.11.1 dependencies.ramda
0.21.x
$ node --print "$(npm view ramda …
```
=> documentation: use version-specific function URLs

index.js
I've realized the Fantasy Land URLs should be anchored to a specific tag. It's misleading to link to whatever is on `master`, particularly since we're currently targeting such an old version of the spec.
=> maybe, either: add Setoid to list of type classes satisfied

karma.conf.js
We'll soon depend on sanctuary-type-classes, which will break IE9 compatibility (sanctuary-js/sanctuary-type-classes#27).
=> karma: replace IE9 with IE10 in test matrix

index.js, test/get.js, test/gets.js, test/parseJson.js
Commit description:
> This commit will close #149 by changing all functions
> that have built-in type validation to use predicates
> instead of TypeReps to perform their validations.
> 
> The functions affected are:
> - get()
> - gets()
> - parseJson()
> 
> The only function untouched is `is()`, for it is used
> to turn a TypeRep into a predicate.
=> Change type validators to use predicate instead of TypeRep

index.js, package.json, test/fromMaybe_.js
=> maybe: add S.fromMaybe_

circle.yml
Now that Node 0.12 is officially end of life we should remove it from our test matrix. I have replaced it with Node 7 but can remove it if we want to speed up build times.
=> remove support for node 0.12

index.js
As a result of #264 the value of `list` in the else branch is guaranteed to be a member of `Array Any` (whereas previously it could have been an `arguments` object or some other array-like object).
=> list: remove unnecessary use of Array#slice

index.js, test/match.js, test/matchAll.js
Closes #253; closes #260
[`String#match`][1] performs one of two very different operations depending on whether the provided regexp has `global` set to `true`:
```javascript
> 'xxx'.match(/x/)
['x', index: 0, input: 'xxx']
> 'xxx'.match(/x/g)
['x', 'x', 'x']
```
Typical JavaScript nonsense! The sane approach, of course, is to provide two functions:
```purescript
match :: NonGlobalRegExp -> String -> Maybe { match :: String, groups :: Array (Maybe String) }
matchAll :: GlobalRegExp -> String -> Array { match :: String, groups :: Array (Maybe String) }
```
Ideally `RegExp` values would not have `global`-ness baked in. One could then use a pattern in different ways depending on one's requirements. Alas, this is not the case. As a result, `match` requires a `RegExp` value with `global` set to …
=> regexp: revise S.match and add S.matchAll

bower.json, index.js, karma.conf.js, package.json, test/Either/Left.js, test/Either/Right.js, test/Maybe/Just.js, test/Maybe/Nothing.js, test/create.js, test/internal/Compose.js, test/internal/Identity.js, test/is.js, test/regex.js, test/type.js
This pull request depends on sanctuary-js/sanctuary-type-identifiers#1. Furthermore, this pull request must not be merged until sanctuary-js/sanctuary-def#112 has been merged, `sanctuary-def@0.9.0` has been published, and Sanctuary has been updated to use that version. Here's the current problem:
```javascript
var $ = require('sanctuary-def');
function Identity(x) {
if (!(this instanceof Identity)) return new Identity(x);
this.value = x;
}
Identity['@@type'] = 'my-package/Identity';
$.Function._test(Math.abs);  // => true
$.Function._test(Identity);  // => false
```
=> move @@type properties to type representatives

index.js, scripts/version-urls
This will be particularly useful when we address #252 as we'll be able to link to the precise version of the Fantasy Land specification we target.
=> documentation: use version-specific project URLs

index.js
The relationship between Sanctuary, Ramda, and even Ramda-fantasy is currently pretty difficult to get a solid grip on for a newcomer like myself. I have found that information is surprisingly difficult to obtain, but in the end I found the relationship clarified very well by @davidchambers in #178. 
Making such a small change to the README would make a huge difference. Maybe a small section along the lines of "Ramda vs. Sancuary" should be added as well, explaining the main differences of using just Ramda, Ramda with monads from Ramda-fantasy, and using Sanctuary. This section could also clarify that one currently has to use Ramda and Sanctuary alongside each other but in the future Sanctuary can be used on its own.
Some examples of the confusion in the community can be seen at [Ramda …
=> Clarify Ramda <-> Sanctuary relationship

index.js
Browserify require static import's in order to establish a dependency tree.
This PR addresses this issue by replacing e.g. `require(deps[0])` with `require('sanctuary-def')`
=> Static imports to aid bundle traversing tools

index.js, test/append.js, test/prepend.js
See #343.
While implementing I assumed `Nothing` and `Left` would annihilate:
```js
S.append(1, S.Nothing) // Nothing
```
The only other thing I could think to do would be to wrap the value in `Just` or `Right`. But that would break the short-circuiting behavior.
=> Generalize append  and prepend

index.js, test/env.js
Based on sanctuary-js/sanctuary-def#123
This fixes the inconsistent type of `env`, allowing it to be passed into `$.test`. We should release this as a patch.
=> Replace Type constructors in env with actual Types

package.json
https://github.com/plaid/transcribe/compare/v0.5.0...v1.0.0
This upgrades us to the latest Transcribe release which features @cust0dian's improvement to the handling of `->` in wrapped type signatures (plaid/transcribe#14).
=> transcribe@1.0.x

index.js, test/dropWhile.js, test/takeWhile.js
=> foldable: add S.takeWhile and S.dropWhile

index.js
These descriptions have been wrong since #216. Oops!
=> maybe, either: fix "fantasy-land/traverse" descriptions

bower.json, index.js, package.json, test/contramap.js, test/filterM.js
https://github.com/sanctuary-js/sanctuary-type-classes/compare/v3.1.0...v4.0.0
:warning: This propagates the breaking change from sanctuary-js/sanctuary-type-classes#37.
=> sanctuary-type-classes@4.0.0

index.js, test/Either/Left.js, test/Either/Right.js, test/Maybe/Just.js, test/Maybe/Nothing.js, test/filter.js
Closes #346
Before:
```javascript
S.concat(S.Just(1), S.Just(1));
// ! TypeError: Semigroup.methods.concat(...) is not a function
```
After:
```javascript
S.concat(S.Just(1), S.Just(1));
// ! TypeError: Type-class constraint violation
//
//   concat :: Semigroup a => a -> a -> a
//             ^^^^^^^^^^^    ^
//                            1
//
//   1)  Just(1) :: Maybe Number, Maybe FiniteNumber, Maybe NonZeroFiniteNumber, Maybe Integer, Maybe ValidNumber
//
//   ‘concat’ requires ‘a’ to satisfy the Semigroup type-class constraint; the value at position 1 does not.
```
Losing the ability to `filter(odd, Just(4))` is a real shame. This happens because `Just(4)` does not satisfy the requirements of Monoid as it does not satisfy the requirements of Semigroup.
It seems we need …
=> maybe, either: define "fantasy-land/concat" conditionally

index.js, test/stripPrefix.js, test/stripSuffix.js
Closes #329
When reviewing, please pay particularly close attention to the `stripSuffix` implementation. Negative indexes impinge on my reasoning ability, but in striking a balance between readability and efficiency I decided not to use `Math.max(0, s.length - suffix.length)` to avoid them.
=> string: add S.stripPrefix and S.stripSuffix

bower.json, index.js, package.json, test/Either/Left.js, test/Either/Right.js, test/Maybe/Just.js, test/Maybe/Nothing.js, test/equals.js, test/gt.js, test/gt_.js, test/gte.js, test/gte_.js, test/internal/Useless.js, test/internal/sanctuary.js, test/lt.js, test/lt_.js, test/lte.js, test/lte_.js
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v5.0.0>
This pull request adds four new functions: `lt`, `lte`, `gt`, and `gte`. It also replaces the internal Ord type class with the one defined in sanctuary-type-classes, making `min` and `max` even more general.
This pull request defines `fantasy-land/lte` for Maybe and Either. These additions will need to be applied to sanctuary-js/sanctuary-maybe#3 and sanctuary-js/sanctuary-either#3 respectively.
Note that `S.equals(0, -0)` will evaluate `true` as a result of this change. Since `-0` is neither less than nor greater than `0`, it must be equal to `0` in order to satisfy the [Ord][1] totality law.
@sadasant, you should be able to resume work on #365 once this pull request has been merged. :)
[1]: …
=> sanctuary-type-classes@5.0.0

index.js, test/find.js
This leads me to believe that sanctuary-type-classes should ensure consistent enumeration order in [`Object$prototype$reduce`][1] (by sorting the keys). Do others agree that this is desirable?
```haskell
> find (const True) (Map.fromList [("x", 0), ("y", 1)])
Just 0
> find (const True) (Map.fromList [("y", 1), ("x", 0)])
Just 0
```
[1]: https://github.com/sanctuary-js/sanctuary-type-classes/blob/v5.0.0/index.js#L862-L867
=> array: generalize S.find

index.js
Hi
Both languages are obviously easily findable on a search engines.
But having proper links offer convenience for people skimming through the README.
=> docs: add links to Haskell and PureScript in README

bower.json, index.js, package.json, test/internal/sanctuary.js, test/type.js
<https://github.com/sanctuary-js/sanctuary-type-identifiers/releases/tag/v2.0.0>
> This commit updates the return type of `S.type`. Those wishing to access unparsed type identifiers can use sanctuary-type-identifiers directly.
=> sanctuary-type-identifiers@2.0.1

bower.json, index.js, package.json, test/sort.js, test/sortBy.js
Closes #353
This takes the `sortBy` implementation from <https://github.com/sanctuary-js/sanctuary/pull/365#issuecomment-298272599>, applies @safareli's improvements from <https://github.com/sanctuary-js/sanctuary/pull/365#issuecomment-300780512>, and further improves the algorithm by using binary search.
`sort` is trivially derived via `sortBy(I)`.
=> array: add S.sort and S.sortBy

index.js, test/elem.js
I just realized we don't have the equivalent of Haskell's [`elem`][1]. We should rectify this. :)
I also just realized that `S.elem(0)` is much nicer than `S.equals(S.Just(0))`!
[1]: http://hackage.haskell.org/package/base-4.9.1.0/docs/Data-Foldable.html#v:elem
=> array: add S.elem

bower.json, package.json
<https://github.com/sanctuary-js/sanctuary-def/releases/v0.12.1>
I don't think this change affects Sanctuary, but keeping dependencies up to date is good practice.
=> sanctuary-def@0.12.1

index.js, test/internal/List.js, test/internal/sanctuary.js, test/reverse.js
:warning: This is a breaking change, as [`reverse`][1] will no longer operate on strings.
This pull request inches us closer to a goal I stated in #411: removing the [List][2] type.
[1]: https://github.com/sanctuary-js/sanctuary/tree/v0.13.2#reverse
[2]: https://github.com/sanctuary-js/sanctuary/tree/v0.13.2#list
=> array: generalize S.reverse

Makefile, scripts/commit-message
Commit summary wrapping (as seen in <https://github.com/sanctuary-js/sanctuary-def/commit/9a1d1a6dc16646fcbf97b75eae66ddd6a5e31c1a>) is unattractive. To avoid it, I check the lengths of my branch names using `wc -c`. I'd like to automate this check. :)
If this pull request is merged I plan to see it in use for several weeks before making the same change to other Sanctuary projects. It would be efficient to make any necessary tweaks *before* duplicating this code.
=> lint: ensure merge commit summary will not exceed 72 characters

bower.json, index.js, package.json, test/parseInt.js, test/type.js
<del>I plan to release `sanctuary-def@0.13.0` in the near future based on what is currently on `master`. I'm opening this pull request before doing so in order to verify the changes.</del>
We can now use `$.Thunk` and `$.Predicate`—added in sanctuary-js/sanctuary-def#161—so we no longer need to define these ourselves.
We can now use `$.NonNegativeInteger`—added by @kurtmilam in sanctuary-js/sanctuary-def#165—to more precisely define the return type of `S.type`.
=> sanctuary-def@0.13.0

index.js, test/get.js, test/gets.js, test/parseJson.js
> These functions facilitate safe interactions with untrusted values. To be maximally useful they should each take a predicate which safely handles any input (even inconsistently typed input).
=> relax constraints on predicates given to S.get, S.gets, and S.parseJson

index.js, test/pow.js, test/pow_.js
These functions sit naturally alongside [`S.sub`][1] and [`S.sub_`][2].
[1]: https://sanctuary.js.org/#sub
[2]: https://sanctuary.js.org/#sub_
=> number: add S.pow and S.pow_

index.d.ts
Definitions like `(any) =>` are untyped params named any (implicit any types) and blow up when building with the noImplicitAny rule turned on. Fixable with placeholder parameter names and explicit types like `(a: any) =>`.
A tsconfig.json that causes the issue:
```json
{
"compilerOptions": {
"target": "ES2017",
"outDir": "dist",
"rootDir": "src",
"moduleResolution": "node",
"module": "commonjs",
"declaration": true,
"importHelpers": true,
"inlineSourceMap": true,
"listFiles": false,
"traceResolution": false,
"pretty": true,
"types": ["node"],
"baseUrl": "src",
"strictNullChecks": true,
"strict": true,
"noImplicitAny": true,
"noImplicitReturns": true,
"noImplicitThis": true,
"noUnusedLocals": true
},
"include": ["src/**/*.ts"],
"exclude": ["node_modules/**"],
"compileOnSave": false
}
``` …
=> Bugfix: TypeScript definitions cause error TS7006 when building with noImplicitAny.

index.js
=> documentation: use ‘fantasy-land/’ prefix when referencing ‘map’ method

test/groupBy.js
By avoiding the expensive type checking performed by `S.equals` we're able to increase the number of test cases generated.
/cc @sadasant
=> test: use Z.equals rather than S.equals in property test for S.groupBy

test/toString.js
Fixes #455
[MDN][1]:
> __Note:__ parsing of date strings with the `Date` constructor (and `Date.parse`, they are equivalent) is strongly discouraged due to browser differences and inconsistencies. Support for RFC 2822 format strings is by convention only. Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local.
@futpib, please confirm that this addresses the issue for you.
[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
=> test: avoid implementation-dependent parsing of date string

index.js, test/singleton.js
Followup from [here](https://github.com/sanctuary-js/sanctuary/issues/434#issuecomment-346505904). Name is up for debate, I think `embed` might be nicer.
Something is wrong with my setup it looks like, because tests explode when I run `npm test`. Punting to the CI.
```
node_modules/.bin/istanbul cover node_modules/.bin/_mocha
No coverage information was collected, exit without writing coverage information
/mnt/d/depot/git/sanctuary/node_modules/.bin/_mocha:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
^^^^^^^
SyntaxError: missing ) after argument list
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:599:28)
at Object.Module._extensions..js (module.js:646:10)
at Object.Module._extensions.(anonymous function) [as .js] …
```
=> Add value constructor for string maps

index.js, test/insert.js, test/remove.js
=> strmap: add S.insert and S.remove

bower.json, package.json, test/sequence.js, test/traverse.js
This brings the fix from sanctuary-js/sanctuary-type-classes#75 to this library, so `S.sequence` and `S.traverse` now behave correctly when applied to string maps.
/cc @masaeedu
=> sanctuary-type-classes@7.1.1

index.js, scripts/version-urls
Remembering to update such things manually is clearly not a good solution.
=> documentation: use placeholder for version-specific type URL

index.js, package.json
Fixes #469
@dakom, does updating your `sanctuary` dependency to `sanctuary-js/sanctuary#4f6826d` fix your issue?
=> hide doctest-specific imports from build tools

index.js
These simplifications could have been included in #232.
=> logic: remove vestigial support for Boolean objects

test/groupBy.js, test/insert.js, test/remove.js, test/splitOn.js, test/splitOnRegex.js
Currently we use a mixture of `equals(lhs)(rhs)`, `S.equals(lhs, rhs)`, and `lhs === rhs`. There's no reason for this inconsistency.
=> test: use equals(lhs)(rhs) form in jsc.assert blocks

index.js, test/get.js, test/gets.js, test/is.js, test/parseJson.js
Closes #502
This pull request greatly increases the expressive power of `S.is` by allowing us to specify types such as `Array (Maybe Integer)` rather than `Array ???`.
If this pull request is accepted, #481 will no longer be warranted.
/cc @futpib, @gautaz, @miwillhite, @najlachamseddine, @tomkel
=> classify: change S.is to take a sanctuary-def Type value

index.js
Currently, each Sanctuary function is defined once for each Sanctuary module created. This pull request restructures the code so that constraints, types, and functions are defined just once.
=> share definitions of constraints, types, and functions

index.js, test/Maybe/Maybe.js, test/at.js, test/drop.js, test/dropLast.js, test/head.js, test/init.js, test/last.js, test/slice.js, test/tail.js, test/take.js, test/takeLast.js
The time has come. :)
The following functions will no longer operate on strings:
- `S.at`
- `S.drop`
- `S.dropLast`
- `S.head`
- `S.init`
- `S.last`
- `S.slice`
- `S.tail`
- `S.take`
- `S.takeLast`
=> array: remove unprincipled List type constructor

eslint/es6.js, index.js, karma.conf.js, test/NODE_ENV.js
In #506, @blackxored has made a case for changing the default value of `checkTypes` from `true` to an expression involving `process.env.NODE_ENV`. I have long opposed this change, but when Aldwin disagrees with me it's wise to reconsider my position. I have done so, and I have changed my mind.
Requirements:
- default Sanctuary module should perform type checking *by default*;
- behaviour must be easy to understand; and
- the user must be permitted to specify whether type checking should be performed.
Although not a requirement, it would be nice to reduce the proportion of users who find it necessary to use [`S.create`][1]. I believe this is your primary goal, Adrian.
The current rule is as follows:
> Type checking is enabled for the default module.
This satisfies the requirements but …
=> disable type checking for default module in "production"

package.json
This deals with several security warnings which appear when running `npm install` with Node 10.
=> karma@2.0.x

index.js
This section has been out of date since #513 was merged. I'm pleased that this section is no longer necessary, as it was always quite confusing.
=> documentation: remove outdated section on type representatives

index.js
>     Before:                         After:
>
>     h1. Sanctuary                   h1. Sanctuary
>       h2. Types                       h2. Types
>       h2. Type checking               h2. Type checking
>       h2. API                         h2. API
>                                         h3. Configure
>           h4. create                      h4. create
>           h4. env                         h4. env
>           h4. unchecked                   h4. unchecked
>         h3. Classify                    h3. Classify
>           h4. type                        h4. type
>           h4. is                          h4. is
>         h3. Showable                    h3. Showable
>           h4. show                        h4. show
>         ... …
=> documentation: fill gap in heading hierarchy

bower.json, index.js, karma.conf.js, package.json, scripts/prepublish, test/Either/Left.js, test/Either/Right.js, test/Maybe/Just.js, test/Maybe/Nothing.js, test/type.js
Now that [sanctuary-maybe][1] and [sanctuary-either][2] have been published we can depend on those packages and remove the Maybe and Either implementations from this project. :D
[1]: https://github.com/sanctuary-js/sanctuary-maybe
[2]: https://github.com/sanctuary-js/sanctuary-either
=> maybe, either: integrate sanctuary-maybe and sanctuary-either

.eslintrc.json, bower.json, index.js, karma.conf.js, package.json, test/Pair.js, test/PairType.js, test/fromPairs.js, test/fst.js, test/pairs.js, test/snd.js, test/swap.js, test/unfoldr.js, test/zip.js
This pull request adds [sanctuary-pair][1] as a dependency, re-exports its functions, and updates several existing functions to use `Pair a b` rather than `Array2 a b`.
```diff
$ git show -U0 index.js | grep '//#'
+  //# PairType :: Type -> Type -> Type
+  //# Pair :: a -> b -> Pair a b
+  //# fst :: Pair a b -> a
+  //# snd :: Pair a b -> b
+  //# swap :: Pair a b -> Pair b a
-  //# unfoldr :: (b -> Maybe (Array2 a b)) -> b -> Array a
+  //# unfoldr :: (b -> Maybe (Pair a b)) -> b -> Array a
-  //# zip :: Array a -> Array b -> Array (Array2 a b)
+  //# zip :: Array a -> Array b -> Array (Pair a b)
-  //# pairs :: StrMap a -> Array (Array2 String a)
+  //# pairs :: StrMap a -> Array (Pair String a)
-  //# fromPairs :: Foldable f => f (Array2 String a) -> StrMap a
+  //# fromPairs :: …
```
=> pair: integrate sanctuary-pair

bower.json, index.js, package.json, test/I.js
- <https://github.com/sanctuary-js/sanctuary-def/releases/tag/v0.18.0>
- <https://github.com/sanctuary-js/sanctuary-def/releases/tag/v0.18.1>
While discussing browser usage in #409, @JAForbes wrote:
> I think we should also explain why such a type isn't included by default.
I don't think we had a good reason for not including a type such as [`$.HtmlElement`][1] in the default environment. With this pull request `S.I (document.body)` works out of the box, saving us from documenting how one could define this type oneself. :)
/cc @krainboltgreene
[1]: https://github.com/sanctuary-js/sanctuary-def#HtmlElement
=> sanctuary-def@0.18.1

index.js
I think foldMap is a great function that has many usages.
However it lacks more examples and people is not used to the concept of giving a typeRep, this tries to make the function more easy to understand with an extra example that uses array.
=> docs(foldMap): added an extra example to foldMap

test/Just.js, test/Left.js, test/Nothing.js, test/Right.js
I went slightly too far in #602. This pull request reinstates the trivial tests for the data constructors.
=> test: add trivial tests for Maybe and Either data constructors

index.js
Closes #488
I used `<blockquote>` rather than the equivalent Markdown syntax, because lines beginning with `>` are treated as doctest input. Ideally, only lines beginning with `>` within `` ```javascript `` code blocks would be evaluated, but [doctest][1] doesn't support this use case.
[1]: https://github.com/davidchambers/doctest
=> parse: document inconsistencies of S.parseDate

index.js, test/pair~.js
This function is similar to the functions added in #592 and #593. The fact that `fst`, `snd`, and `swap` can be defined in terms of `pair` demonstrates the foundational nature of `pair`.
__test/pair~.js__ is horribly named for compatibility with case-insensitive file systems. ;)
/cc @puffnfresh
=> pair: add S.pair

index.js, test/head.js, test/init.js, test/last.js, test/tail.js
Closes #570
Initial attempt to generalize head, tail, last and init functions for Foldables.
=> array: generalize S.head, S.last, S.tail, and S.init

index.js, test/internal/strMap.js, test/keys.js, test/pairs.js, test/value.js, test/values.js
Closes #611
Please let me know if you prefer `lookup` or some other name.
/cc @daaaaa
=> strmap: add S.value

index.js, test/dropWhile.js, test/takeWhile.js
As explained in sanctuary-js/sanctuary-type-classes#122, these functions are currently unsound. `Z.takeWhile` and `Z.dropWhile` are to be removed in sanctuary-js/sanctuary-type-classes#123. `S.takeWhile` and `S.dropWhile` are useful functions, so it would be a shame to lose them entirely. Instead, let's specialize them.
=> array: specialize S.takeWhile and S.dropWhile

index.js, test/alt.js
The “default” argument should come first, as it's more likely to be known in advance.
=> fantasy-land: flip S.alt argument order

index.js
These type constructors were removed in #626, but I forgot to remove the associated documentation.
=> documentation: remove references to defunct type constructors

index.js
Before:
- `take :: Integer -> Array a -> Maybe (Array a)`
- `takeLast :: Integer -> Array a -> Maybe (Array a)`
- `takeWhile :: (a -> Boolean) -> Array a -> Array a`
- `drop :: Integer -> Array a -> Maybe (Array a)`
- `dropLast :: Integer -> Array a -> Maybe (Array a)`
- `dropWhile :: (a -> Boolean) -> Array a -> Array a`
After:
- `take :: Integer -> Array a -> Maybe (Array a)`
- `drop :: Integer -> Array a -> Maybe (Array a)`
- `takeLast :: Integer -> Array a -> Maybe (Array a)`
- `dropLast :: Integer -> Array a -> Maybe (Array a)`
- `takeWhile :: (a -> Boolean) -> Array a -> Array a`
- `dropWhile :: (a -> Boolean) -> Array a -> Array a`
=> array: reorder S.take* and S.drop* definitions

index.js, test/drop.js, test/take.js
The code is more complex than I would like it to be, but I believe the complexity is necessary. Please correct me if I'm wrong about this! :)
=> array: generalize S.take and S.drop

index.js, test/dropLast.js, test/takeLast.js
The implementations are not as efficient as they could be, but I want to avoid spreading complexity currently confined to `_takeDrop`.
=> array: generalize S.takeLast and S.dropLast

index.js
I discovered recently that I've been misusing _which_ for decades.
<https://www.grammarly.com/blog/which-vs-that/>:
> A defining clause […] gives information essential to the meaning of the sentence. _That_ is used in defining clauses.
=> documentation: use “that” rather than “which” in defining clauses

index.js, test/size.js
This is a breaking change if functions' string representations are considered part of the public API, but they are primarily for use in the REPL. Are others comfortable with this change being included in a minor or patch release?
=> array: update return type of S.size

index.js, scripts/generate-readme
=> documentation: prefix heading identifiers to avoid collisions

scripts/bundle
`scripts/bundle`, added in #641, currently uses the value of the `version` field of __package.json__ when generating the header. This is incorrect: xyz runs scripts *before* updating the `version` field. This explains why the first line of [__bundle.js__][1] refers to version `2.0.1` rather than to version `2.0.2`.
/cc @Avaq
[1]: https://github.com/sanctuary-js/sanctuary/blob/v2.0.2/dist/bundle.js
=> dist: use VERSION when generating bundle header

index.js, test/reduce.js, test/reduce_.js
I've wanted this function many times during the past few years. @sanctuary-js/owners, are you in favour of this addition?
=> fantasy-land: add S.reduce_

index.js
`maybe` and `either` are fundamental functions, so they should be introduced before their more specialized relatives.
=> maybe, either: reorder functions

index.js, test/fromLeft.js, test/fromRight.js
Forgot why I never opened this, but I can't see a reason to not push it forward. Let me know if there is anything you'd like me to add / change etc.
Summary of changes: Add functionality of `fromLeft` and `fromRight`
`fromLeft :: a -> Either a b -> a`
`fromRight :: b -> Either a b -> b`
=> fromLeft and fromRight

index.js, test/fromEither.js
https://github.com/sanctuary-js/sanctuary/pull/644#issuecomment-671040530
=> Change the meaning of `fromEither`

.circleci/config.yml, index.js, test/.eslintrc.json, test/replace.js
Supersedes #686
This pull request adds the following function:
```haskell
replace :: (Array (Maybe String) -> String) -> RegExp -> String -> String
```
In <https://github.com/sanctuary-js/sanctuary/pull/686#discussion_r466296798>, @Avaq made a strong case for naming this more general function `replace`. @Avaq also noted that the specialized function, `replaceWith`, is trivially derivable from `replace`. For this reason I decided not to include `replaceWith` in this pull request; it could easily be added in the future if `replace (K ('...'))` proves irksome.
I have opened sanctuary-js/sanctuary-site#90 to provide several examples of `replace` in use.
=> regexp: add S.replace

index.js, test/findMap.js
Supersedes #697
With [`find`][1] one sometimes applies a transformation to determine whether an element is suitable only to apply the transformation a second time if a suitable element is found:
```javascript
> S.chain (S.parseInt (16))
.         (S.find (S.compose (S.isJust) (S.parseInt (16)))
.                 (['A', 'B', 'C']))
Just (10)
```
With `findMap` the transformation is provided just once:
```javascript
> S.findMap (S.parseInt (16)) (['A', 'B', 'C'])
Just (10)
```
[1]: https://sanctuary.js.org/#find
=> array: add S.findMap

index.js, test/elem_.js
I find myself flipping [`elem`][1] quite often.
Do you agree with this addition?
[1]: https://sanctuary.js.org/#elem
=> array: add S.elem_

.eslintrc.json, index.js
sanctuary-js/sanctuary-site#92
In addition to documenting the use of [`lift2`][1] and [`lift3`][2] as combinators, this pull request standardizes the steps for deriving signatures of combinators from more general signatures:
1.  Provide general signature:
```haskell
Functor f => (a -> b) -> f a -> f b
```
2.  Replace type variable with `Function x`:
```haskell
(a -> b) -> Function x a -> Function x b
```
3.  Convert to `->` form:
```haskell
(a -> b) -> (x -> a) -> (x -> b)
```
4.  Remove unnecessary parentheses:
```haskell
(a -> b) -> (x -> a) -> x -> b
```
5.  Rename type variables:
```haskell
(b -> c) -> (a -> b) -> a -> c
```
[1]: https://sanctuary.js.org/#lift2
[2]: https://sanctuary.js.org/#lift3
=> fantasy-land: document use of S.lift2 and S.lift3 as combinators

.eslintrc.json, index.js, scripts/.eslintrc.json, test/.eslintrc.json
=> use ES6 syntax

test/groupBy.js, test/insert.js, test/internal/eq.js, test/internal/equals.js, test/internal/throws.js, test/match.js, test/none.js, test/remove.js, test/splitOn.js, test/splitOnRegex.js
This pull request reduces indirection in the test suite by using `Z.equals` directly in place of the curried wrapper function.
=> remove test/internal/equals module

index.js
These are not breaking changes as [`String.prototype.startsWith`][1] and [`String.prototype.endsWith`][2] are ES6 features.
[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith
[2]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith
=> simplify `stripPrefix` and `stripSuffix`
