sanctuary-js/sanctuary

- index.js
- test/index.js
> parse: add S.parseJson

- index.js
- test/index.js
Is this a step in the right direction do you think, @buzzdecafe?
> monad: remove S.bind and S.then in favour of R.chain compatibility

- index.js
- test/index.js
No good can come of an "Invalid Date" object.
> parse: add S.parseDate

- index.js
- test/index.js
Similar to [`R.find`][1] but uses Maybe to encode success/failure, rather than relying on null/undefined.
[1]: http://ramdajs.com/docs/#find
> list: add S.find

- index.js
- test/index.js
Reading fantasyland/fantasy-land#85 improved my understanding of these types, and motivated me to add the methods necessary for Maybe to implement the Apply, Applicative, Chain, and Monad specifications.
> maybe: implement Apply, Applicative, Chain, and Monad

- index.js
- test/index.js
> Add S.pluck functionality

- index.js
- test/index.js
> `S.and`, `S.or`, and `S.xor` are defined in terms of a private `toBoolean` function which dispatches to each operand's `toBoolean` method if available. `Just.prototype.or` and `Nothing.prototype.or` are no longer necessary so are removed in this commit.
I don't know whether `S.xor` will be useful in practice, but I know how to find out. :)
> control: add S.and and S.xor

- index.js
- test/index.js
I *think* this is correct, but I'd greatly appreciate a review.
> either: implement Apply, Applicative, Chain, and Monad

- test/index.js
This makes assertions for functions which may throw a bit less offensive. :)
> test: point-free predicates

- index.js
- test/index.js
> Add indexOf function

- index.js
- test/index.js
As discussed in #39. This actually turned out to be more difficult than anticipated, I think I've managed to test all the edge cases.
> Add Slice Function

- index.js
- test/index.js
As discussed in #39 . There's a few parts of this PR that need clarifying. I'm not sure if I've got the type signature right and I didn't know whether to group the string and array tests separately. Also, should there be more tests and documentation around passing negative values to the function?
> add drop and take functions

- index.js
- package.json
- test/index.js
Thanks to ramda/ramda#1096, upgrading to [Ramda v0.15.0][1] gives our types value-based equality!
[1]: https://github.com/ramda/ramda/issues/1186
> value-based equality

- index.js
- test/index.js
> parse: disallow invalid characters in S.parseInt

- index.js
As much as possible I'd like the source code to be a good example of Sanctuary *usage*.
> style: avoid unnecessary use of "new"

- index.js
- test/index.js
My first attempt was `R.pipe(Number, R.equals(-0))`, but this evaluates true when applied to `'-0'`.
> handle new Number(-0) in S.slice, S.take, and S.drop

- index.js
- test/index.js
Adds functions referred to by #66 to bring Sanctuary up to date with Ramda 0.17.
> add takeLast and dropLast

- index.js
- test/index.js
Not sure what I'm doing wrong, but despite the tests passing when run manually, running `make test` reports:
```
sanctuary/index.js:110
return x != null && Object(x) instanceof type;
^
TypeError: Expecting a function in instanceof check, but got undefined
at _is (sanctuary/index.js:110:46)
at Just.<anonymous> (sanctuary/index.js:164:21)
at Just.map (sanctuary/index.js:116:45)
at [stdin]:63:25
at Object.exports.runInThisContext (vm.js:74:17)
at Object.<anonymous> ([stdin]-wrapper:6:22)
at Module._compile (module.js:460:26)
at evalScript (node.js:431:25)
at Socket.<anonymous> (node.js:164:11)
at Socket.emit (events.js:129:20)
```
> Adds Maybe#reduce.

- index.js
- test/index.js
> maybe: add S.maybe

- index.js
- test/index.js
Supersedes ramda/ramda#1382
See [Data.String][1] from the Haskell Prelude.
[1]: https://hackage.haskell.org/package/base-4.8.1.0/docs/Data-String.html#g:1
> string: add S.words, S.unwords, S.lines, and S.unlines

- index.js
- test/index.js
I've been meaning to add this function for some time. @lucamartinetti asked me today whether such a function exists, prompting this pull request.
My only question is which of the following is the best combination of names:
| `(* -> a) -> (* -> Maybe a)`  | `(* -> a) -> (* -> Either Error a)` |
| ----------------------------- | ----------------------------------- |
| `encase`                      | `encaseEither`                      |
| `encaseMaybe`                 | `encase`                            |
| `encaseMaybe`                 | `encaseEither`                      |
I don't have a strong inclination in any direction, so I'm inclined to leave `S.encase` alone. Does anyone have a strong preference for one of the other options?
> either: add S.encaseEither

- bower.json
- package.json
See #88
I used Bower's guide to [creating packages][1] as a reference.
Could you review this change, @ChetHarrison?
[1]: http://bower.io/docs/creating-packages/
> bower: add bower.json

- index.js
- test/index.js
> make exported functions throw if applied to too many arguments

- Makefile
- index.js
Just a few minor changes to the documentation in preparation for v0.7.0. :)
> documentation tweaks

- Makefile
- index.js
- package.json
I'm pleased to be able to say goodbye to the `sed` pipeline at last.
> integrate doctest

- index.js
- test/index.js
Closes #100
> `S.is`, `S.get`, `S.gets`, and `S.pluck` now ignore constructor identity, allowing them to operate on objects from other environments, such as iframes and sandboxes. Additionally, packages which export functions which take and/or return values of Sanctuary types no longer rely on npm package deduplication to satisfy the requirements of Sanctuary's run-time type checking.
>
> Since `instanceof` checks are no longer acceptable, `S.is` no longer respects subtyping.
>
> This [pull request] also introduces the following functions:
>
> ```haskell
> type      :: a -> String
> isNothing :: Maybe a -> Boolean
> isJust    :: Maybe a -> Boolean
> isLeft    :: Either a b -> Boolean
> isRight   :: Either a b -> Boolean
> ```
> do not rely on constructor identity

- index.js
- test/index.js
I tried to avoid using `S.test` again by using `Just#equals` but that function depends on `this` so the context got messed up when passed into `R.ifElse`.
> Add ifElse function

- index.js
- test/index.js
> maybe, either: simplify S.encase and S.encaseEither

- index.js
- test/index.js
Following my gitastrophe in the intitial pull request for this (#116), here's the new version off `master`. :relieved:
> Add flip function (again)

- index.js
- test/index.js
@davidchambers, Wanted to see you what thought of `S.lift` before I go ahead and throw in `S.lift2` and `S.lift3`.
`S.lift` is pretty much just a wrapper for `R.map`, but `S.lift2` and `S.lift3` also use `R.ap`.
> add lift, lift2, lift3

- circle.yml
As per plaid/sanctuary-def/pull/22.
> Test new versions of Node

- index.js
- package.json
- test/index.js
Depends on plaid/sanctuary-def#4
Type class constraints obviate the need for ad hoc type checking via `assertMethodExists`, as demonstrated by the changes to `Maybe#concat` below.
Before:
```javascript
//  Nothing#concat :: Maybe a ~> Maybe a -> Maybe a
Nothing.prototype.concat = def('Nothing#concat', [Maybe], function(maybe) {
if (maybe.isJust) {
assertMethodExists('concat', maybe.value);
}
return maybe;
});
//  Just#concat :: Maybe a ~> Maybe a -> Maybe a
Just.prototype.concat = def('Just#concat', [Maybe], function(maybe) {
assertMethodExists('concat', this.value);
if (maybe.isJust) {
assertMethodExists('concat', maybe.value);
return Just(this.value.concat(maybe.value));
} else {
return this;
}
});
```
After:
```javascript
Maybe.prototype.concat =
method('Maybe#concat',
{a: …
```
> integrate sanctuary-def

- index.js
- test/index.js
As discussed in #127. I'll do `mult` and `div` later because I can't face editing all those `Semigroup`/`Monoid` error messages with a hangover. :laughing:
> Add S.inc and S.dec functions

- index.js
- test/index.js
Last of the functions from #127. I never want to see another `concat` error message again!
> Add div and mult functions

- index.js
- test/index.js
```haskell
negate :: ValidNumber -> ValidNumber
```
[`R.negate`][1], but with type checking. :)
[1]: http://ramdajs.com/docs/#negate
> number: add S.negate

- index.js
> Use $.Array Instead of List for S.pipe and S.meld

- index.js
- test/index.js
As discussed in svozza/sanctuary-date-poc-2/pull/1.
> export Maybe and Either types

- index.js
- test/index.js
For #139
* Add the A combinator
* Add the C combinator
* Add the B combinator
* Add the S combinator
> More combinators

- index.js
- test/index.js
This may be of interest to you, @svozza, given your recent work on various date libraries. :)
> ValidDate satisfies the requirements of Ord

- package.json
https://github.com/plaid/transcribe/compare/v0.3.0...v0.4.0
This will give us intelligent wrapping of long type signatures, thanks to plaid/transcribe#10. I'll publish a patch release in the near future (after merging this pull request and one other) as these readme changes are of significance to [sanctuary-site][1].
[1]: https://github.com/plaid/sanctuary-site
> transcribe@0.4.x

- index.js
These changes are required in order for [sanctuary-site][1]'s build script to execute successfully.
[1]: https://github.com/plaid/sanctuary-site
> tweak doctests and implementation for vm.runInNewContext compatibility

- test/index.js
> test: remove line wrapping

- bower.json
- index.js
- package.json
- test/index.js
> ramda@0.20.x

- bower.json
- package.json
> ramda@0.21.x

- index.js
- test/index.js
> string: add S.trim

- circle.yml
This reduces the amount of time the tests take to run on CircleCI by about 50%. :)
> circle: enable parallel testing

- index.js
- test/encase2.js
- test/encase2_.js
- test/encase3.js
- test/encase3_.js
- test/encaseEither2.js
- test/encaseEither2_.js
- test/encaseEither3.js
- test/encaseEither3_.js
- test/reduce.js
- test/reduce_.js
- test/utils.js
Opened this to restart the conversation in #163 
Does not currently expose additional functions that are uncurry-safe
> Changes higher order functions to expect curried functions

- index.js
- test/Either/Either.js
- test/Either/Left.js
- test/Either/Right.js
- test/Maybe/Maybe.js
Closes #120
This is similar to #121. You're the best person to review this patch, @scott-christopher (though others are of course welcome to do so).
> either: implement Traversable

- index.js
- test/range.js
This'll check one more box in #145.
> array: add S.range

- index.js
Closes #235
Does this change look good to you, @kedashoe?
> function: tweak description of S.flip

- index.js
Closes #236
Does this change look good to you, @kedashoe?
> function: tweak descriptions of S.lift2 and S.lift3

- bower.json
- package.json
Closes #243
ramda/ramda#1850
/cc @johannestroeger
> ramda@0.22.x

- index.js
> The List type constructor enables each polymorphic array/string function to be represented by a single type signature (parametrically polymorphic functions do not require such shenanigans).
>
> `List` is poorly defined, as evidenced by its lengthy explanation. Its use should be limited.
>
> This commit also updates type signatures to use `List _` rather than `[_]` to represent the type of an array/string value.
> list: make the List type constructor simpler and more restrictive

- package.json
https://github.com/plaid/transcribe/compare/v0.4.0...v0.5.0
> transcribe@0.5.x

- index.js
Are you happy with these changes, @rjmk?
> documentation: tweak descriptions of higher-order function variants

- test/I.js
- test/properties.js
I imagine that there's a lot of stuff here that people feel
strongly about. Is a `properties` file OK? The naming of the
arbitraries? Using "is idempotent" rather than "satisfies
idempotency"? I thought it would be useful to have a concrete
example to discuss
> Adds property tests for `S.I`

- index.js
Currently methods are defined in alphabetical order. It's more helpful to use dependency-based ordering. This means, for example, that `Maybe#ap` is defined after `Maybe#map` since [Apply][1] depends on [Functor][2]. I used the same order used in [sanctuary-type-classes][3].
[1]: https://github.com/fantasyland/fantasy-land#apply
[2]: https://github.com/fantasyland/fantasy-land#functor
[3]: https://github.com/sanctuary-js/sanctuary-type-classes
> maybe, either: dependency-based method ordering

- index.js
- test/maybe_.js
closed https://github.com/sanctuary-js/sanctuary/issues/284. Here the disscussion: how we should call
the function if Maybe known to be Nothing? If we call it without argument, then If we do:
```
S.maybe(S.K(0), R.length, S.Nothing) // it return a function because S.K still wait one more argument
``` 
The first implementation just call the function without argument, let me know if we want to update it.
> added S.maybe_ function

- index.js
- test/Either/Either.js
- test/Either/Left.js
- test/Either/Right.js
- test/Maybe/Just.js
- test/Maybe/Maybe.js
- test/Maybe/Nothing.js
- test/is.js
This obviates the need for the sentinel value. :)
How does this look to you, @safareli?
> maybe, either: make type representatives uncallable

- README.md
- index.js
I think it's useful to be able to direct people to our Gitter room as it can be a great way for people new to Sanctuary to get information and advice on issues they might be facing.
> Add gitter badge to readme

- Makefile
- index.js
- karma.conf.js
- package.json
- test/Either/Either.js
- test/Either/Left.js
- test/Either/Right.js
- test/Maybe/Just.js
- test/Maybe/Maybe.js
- test/Maybe/Nothing.js
- test/internal/eq.js
- test/internal/throws.js
- test/is.js
- test/lift2.js
- test/pairs.js
- test/regex.js
- test/type.js
- test/unfoldr.js
https://github.com/sanctuary-js/sanctuary-style/compare/v0.3.0...v0.4.0
> sanctuary-style@0.4.x

- index.js
Thanks to @syaiful6 for spotting these errors. :)
> maybe, either: fix "extend" type signatures

- index.js
I overlooked this signature when creating #259.
> maybe: fix signature of Maybe.empty

- index.js
- test/props.js
Closes #295. I wasn't sure about the text for the error message so I figured we could just bikeshed it in the PR here.
> Add S.props

- index.js
- test/Either/Either.js
- test/Either/Left.js
- test/Either/Right.js
- test/internal/laws/Bifunctor.js
- test/internal/laws/bimap.js
- test/internal/laws/index.js
Closes #98
You're likely the best person to review this, @scott-christopher. :)
> either: implement Bifunctor

- index.js
These were mistakenly removed in #312.
> maybe, either: reinstate prefixes

- index.js
- test/Either/Either.js
- test/Maybe/Maybe.js
- test/internal/laws/Alt.js
- test/internal/laws/Alternative.js
- test/internal/laws/Monoid.js
- test/internal/laws/Plus.js
- test/internal/laws/alt_.js
- test/internal/laws/index.js
Could you check the laws, @safareli?
> maybe: define "fantasy-land/zero"

- index.js
- test/complement.js
> Add S.complement

- index.js
- test/unless.js
- test/when.js
> logic: add S.when and S.unless

- bower.json
- index.js
- package.json
- test/ap.js
Closes #361
https://github.com/sanctuary-js/sanctuary-type-classes/compare/v3.0.1...v3.1.0
/cc @gabejohnson
> sanctuary-type-classes@3.1.0

- index.js
> composition: note that S.on is the P combinator

- index.js
- test/tagBy.js
Closes #350.
Sorry for my slowness!
> either: add tagBy

- index.js
- test/pluck.js
> array: generalize S.pluck

- bower.json
- package.json
- test/env.js
- test/internal/sanctuary.js
<https://github.com/sanctuary-js/sanctuary-def/releases/tag/v0.10.0>
> sanctuary-def@0.10.1

- index.js
- test/groupBy.js
- test/groupBy_.js
Should work as in Haskell!
Some notes:
- This can be do in many different ways! Please give feedback
so it can be improved \o/
Please review 🙏🙇
Closes: #351
> groupBy as in Haskell

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-def/releases/tag/v0.11.0>
> sanctuary-def@0.11.0

- index.js
- test/splitOnRegex.js
Closes #339 
Would appreciate some feedback please, especially on the description.
> string: add S.splitOnRegex

- bower.json
- index.js
- package.json
- test/reduce.js
- test/sequence.js
- test/traverse.js
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v5.1.0>
> sanctuary-type-classes@5.1.0

- bower.json
- index.js
- package.json
- test/compose.js
- test/id.js
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v5.2.0>
<del>I'd like to wait until sanctuary-js/sanctuary-type-classes#56 is merged before releasing `sanctuary-type-classes@5.2.0`, at which point I will update this pull request.</del>
> sanctuary-type-classes@5.2.0

- bower.json
- index.js
- package.json
- test/extend.js
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/v6.0.0>
> sanctuary-type-classes@6.0.0

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-def/releases/v0.12.0>
> sanctuary-def@0.12.0

- index.js
- test/groupBy_.js
In the interest of minimizing noise I'm opening a long-running "tweaks" pull request which I'll merge shortly before the next release.
> style: tweaks

- index.js
- test/parseDate.js
Resolves https://github.com/sanctuary-js/sanctuary/issues/406
> parse: parseDate return changed to Maybe ValidDate

- index.js
- test/get.js
- test/gets.js
- test/pluck.js
- test/prop.js
- test/props.js
I'm excited by the possibility of removing the Accessible type class. Let me know if you can think of any reasons not to do so. I have a feeling you will have a lot to say about this pull request, @Avaq.
> remove Accessible type class

- index.js
- test/div.js
- test/div_.js
> number: flip S.div argument order

- index.js
This is the result of discussion in sanctuary-js/sanctuary-type-classes#65.
> strmap: add StrMap heading and description

- index.js
I extracted these changes from #429 as they're not directly related to that pull request.
> documentation: advise against direct use of ‘fantasy-land’ methods

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-def/releases/tag/v0.13.1>
> sanctuary-def@0.13.1

- index.js
- test/allPass.js
- test/anyPass.js
@gabejohnson suggested this improvement on Gitter a few minutes ago. :)
> logic: generalize S.allPass and S.anyPass

- bower.json
- index.js
- package.json
- test/size.js
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v6.1.0>
> sanctuary-type-classes@6.1.0

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v7.0.0>
> sanctuary-type-classes@7.0.0

- bower.json
- index.js
- package.json
- test/internal/Sum.js
- test/internal/sanctuary.js
- test/invert.js
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v7.1.0>
> sanctuary-type-classes@7.1.0

- bower.json
I forgot to make this change in #451.
> circle: update ignore path in bower.json

- .eslintrc.json
- Makefile
- package.json
- scripts/version-urls
<https://github.com/sanctuary-js/sanctuary-style/releases/tag/v1.0.0>
> sanctuary-style@1.0.x

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-def/releases/v0.14.0>
> sanctuary-def@0.14.0

- index.js
- test/pipe.js
This change has been discussed in #472.
> composition: generalize S.pipe

- index.js
- test/pipeK.js
> composition: add pipeK

- bower.json
- index.js
- package.json
- test/duplicate.js
- test/extend.js
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v7.2.0>
> sanctuary-type-classes@7.2.0

- index.js
- test/justs.js
- test/lefts.js
- test/rights.js
<https://github.com/sanctuary-js/sanctuary/issues/489#issuecomment-366982183>
> filterable: generalize S.justs, S.lefts, and S.rights

- index.js
- test/mapMaybe.js
> maybe: generalize S.mapMaybe

- bower.json
- index.js
- package.json
- test/mapLeft.js
Closes #476
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v8.1.0>
> sanctuary-type-classes@8.1.1

- index.js
- test/A.js
<https://github.com/sanctuary-js/sanctuary/issues/438#issuecomment-371809619>
> placeholder: remove S.__

- karma.conf.js
> karma: upgrade iOS in test matrix

- package.json
<https://github.com/sanctuary-js/sanctuary-scripts/releases/tag/v1.1.0>
> sanctuary-scripts@1.1.x

- index.js
- test/internal/pair.js
- test/zip.js
- test/zipWith.js
Work in progress for zipWith!
I started with Ramda’s code (a single while) but switched to Z.reduce to take in count it’s capabilities over different types.
<del>Related to #337</del> <ins>Closes #337</ins>
Please give me feedback! I’m ready to improve this 🤗
> array: add S.zip and S.zipWith

- package.json
- scripts/prepublish
<https://github.com/sanctuary-js/sanctuary-scripts/releases/tag/v1.3.0>
> sanctuary-scripts@1.3.x

- index.js
This pull request also replaces a stray reference to `Pair` with `Array2`.
> define internal functions for deriving functions from methods

- package.json
<https://github.com/browserify/browserify/compare/13.1.1...v16.2.2>
> browserify@16.2.x

- bower.json
- karma.conf.js
- package.json
- test/is.js
<https://github.com/sanctuary-js/sanctuary-def/releases/tag/v0.17.0>
> sanctuary-def@0.17.0

- index.js
Closes #526
/cc @derrickbeining
> documentation: various fixes and improvements

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v9.0.0>
> sanctuary-type-classes@9.0.0

- .eslintrc.json
- package.json
<https://github.com/sanctuary-js/sanctuary-scripts/releases/tag/v2.0.0>
> sanctuary-scripts@2.0.x

- bower.json
- karma.conf.js
- package.json
<https://github.com/sanctuary-js/sanctuary-def/releases/tag/v0.17.1>
> sanctuary-def@0.17.1

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-def/releases/tag/v0.17.2>
> sanctuary-def@0.17.2

- .eslintrc.json
- index.js
Closes #409
/cc @krainboltgreene
> documentation: add installation instructions

- index.js
Closes #366
Is this an accurate characterization of Folktale, @robotlolita? Is there anything you would like to add?
> documentation: state primary difference between Folktale and Sanctuary

- index.js
I just shared an example on Gitter, then realized it's much better than what we currently have. :)
> array: improve S.unfoldr example

- index.js
- test/boolean.js
> logic: add S.boolean

- .eslintrc.json
- index.js
- test/array.js
Closes #581 (in conjunction with #592)
> array: add S.array

- bower.json
- index.js
- package.json
- test/all.js
- test/any.js
- test/clamp.js
- test/none.js
Closes #574
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v10.0.0>
> sanctuary-type-classes@10.0.0

- package.json
<https://github.com/sanctuary-js/sanctuary-descending/releases/tag/v1.1.0>
> sanctuary-descending@1.1.0

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-either/releases/tag/v1.1.0>
> sanctuary-either@1.1.0

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-maybe/releases/tag/v1.1.0>
> sanctuary-maybe@1.1.0

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-pair/releases/tag/v1.1.0>
> sanctuary-pair@1.1.0

- index.js
- package.json
<del>`sanctuary-scripts@3.2.0` has not yet been released, so this pull request is not yet ready to merge.</del>
<del>I want to verify that sanctuary-js/sanctuary-scripts#28 works as intended.</del>
<ins><https://github.com/sanctuary-js/sanctuary-scripts/releases/tag/v3.2.0></ins>
> sanctuary-scripts@3.2.x

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v11.0.0>
> sanctuary-type-classes@11.0.0

- package.json
<https://github.com/sanctuary-js/sanctuary-descending/releases/tag/v1.2.0>
> sanctuary-descending@1.2.0

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-pair/releases/tag/v1.2.0>
> sanctuary-pair@1.2.0

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-either/releases/tag/v1.2.0>
> sanctuary-either@1.2.0

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-maybe/releases/tag/v1.2.0>
> sanctuary-maybe@1.2.0

- .circleci/config.yml
Do you understand the CircleCI error, Aldwin? I think it's related to your recent doctest changes.
> circle: update Node versions

- bower.json
- package.json
<https://github.com/sanctuary-js/sanctuary-def/releases/tag/v0.20.1>
> sanctuary-def@0.20.1

- scripts/.eslintrc.json
- scripts/bundle
- scripts/lint
- scripts/prepublish
Closes #613; closes #480; closes #443; closes #442
Should the files be included in the GitHub repository? The npm package? Both?
|                           | GitHub repository | npm package       |
| ------------------------- |:-----------------:|:-----------------:|
| __dist/bundle.js__        | :question:        | :question:        |
| __dist/bundle.min.js__    | :question:        | :question:        |
/cc @loveship00, @mfidemraizer
> dist: add script for generating bundle with dependencies

- index.js
- test/encase.js
- test/internal/factorial.js
> either: generalize S.encase to permit a value of any type to be thrown

- index.js
- package.json
- test/internal/List.js
- test/internal/Sum.js
- test/internal/sanctuary.js
- test/type.js
<https://github.com/sanctuary-js/sanctuary-type-identifiers/releases/tag/v3.0.0>
> sanctuary-type-identifiers@3.0.0

- .eslintrc.json
- index.js
- package.json
- test/intercalate.js
Closes #360; closes #569
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v12.1.0>
/cc @masaeedu, @syaiful6
> sanctuary-type-classes@12.1.0

- package.json
<https://github.com/sanctuary-js/sanctuary-descending/releases/tag/v2.0.0>
> sanctuary-descending@2.0.0

- package.json
<https://github.com/sanctuary-js/sanctuary-identity/releases/tag/v2.0.0>
> sanctuary-identity@2.0.0

- package.json
<https://github.com/sanctuary-js/sanctuary-either/releases/tag/v2.1.0>
> sanctuary-either@2.1.0

- package.json
<https://github.com/sanctuary-js/sanctuary-maybe/releases/tag/v2.1.0>
> sanctuary-maybe@2.1.0

- package.json
<https://github.com/sanctuary-js/sanctuary-pair/releases/tag/v2.1.0>
> sanctuary-pair@2.1.0

- package.json
<https://github.com/sanctuary-js/sanctuary-descending/releases/tag/v2.1.0>
> sanctuary-descending@2.1.0

- package.json
<https://github.com/sanctuary-js/sanctuary-identity/releases/tag/v2.1.0>
> sanctuary-identity@2.1.0

- index.js
Thanks to #641, adding Sanctuary to a website is now much less fiddly. :)
> documentation: update installation instructions

- package.json
<https://github.com/sanctuary-js/sanctuary-def/releases/tag/v0.21.1>
> sanctuary-def@0.21.1

- index.js
Supersedes #679
How does this look to you, @sugoidesune?
> documentation: promote jsDelivr in installation instructions

- index.js
- package.json
@jceb recently requested the addition of [`$.Buffer`][1] in #575.
/cc @Ken-LiuL
[1]: https://github.com/sanctuary-js/sanctuary-def#Buffer
> sanctuary-def@0.22.0

- package.json
- test/mocha.opts
<https://github.com/sanctuary-js/sanctuary-scripts/releases/tag/v5.0.0>
> sanctuary-scripts@5.0.x

- index.js
I'd like to reduce interdependence to make __index.js__ easier to split into modules.
> inline `toObject`

- index.js
- test/matchAll.js
- test/splitOnRegex.js
- test/test.js
I'd like to reduce interdependence to make __index.js__ easier to split into modules.
> inline `withRegex`

- index.js
I'd like to reduce interdependence to make __index.js__ easier to split into modules.
> inline `_takeDrop`

- test/I.js
This pull request removes the test added in #564 which has been inactive since #603.
> remove vestigial test

- test/chainRec.js
- test/flip.js
- test/internal/curry2.js
- test/internal/map.js
This pull request removes two unnecessary internal modules.
> remove test/internal/curry2 and test/internal/map modules
